### ISSUE TITLE
vue-select async search

### ISSUE THREAD

**Issue by dcastrili** [laravel-enso/FormBuilder#10]
Hi,

I see that you are extending the plugin vue-multiselect on the component vue-select. I wonder if that component is making use of the async search? or should I use it directly from multiselect component?

**Comment by aocneanu** [comment]
Hi,

Please be more explicit.

**Comment by dcastrili** [comment]
What I need to do is to load the dropdown menu with data asynchronously, instead of loading the whole collection at once. Every search will perform a query.

**Comment by aocneanu** [comment]
`VueSelect` is a wrapper for `vue-multiselect` that adds among other features what you are looking for.

You can use `vue-multiselect` w/o using the wrapper and make a simple implementation for the async fetch yourself. Find more details here https://vue-multiselect.js.org/#sub-asynchronous-select

**Comment by dcastrili** [comment]
Yes! 

I have been thru `vue-multiselect` already, but I was wondering if your wrapper was supporting w/o

Thanks for ur feedback 👍
