### ISSUE TITLE
Question about v-model property

### ISSUE THREAD

**Issue by dcastrili** [laravel-enso/FormBuilder#12]
Hi,

I am using the form builder package in `laravel/enso`. Which is very useful and time saving.

I wonder how can I get the `v-model` property name of an element such as `input=text` ? 

I need to set some dinamic values for the form elements in `create.vue`

I am using the `vue-form` component. 

Digging into the source code, I found out that the property name  is `v-model="field.value"` but this value according to the template `form.json` is actually the value of the input right?

something like: 
```html
<input type="text" name="example" value="hello world">
```
So v-model will be `v-model="hello world"`

Below the sample code for `create.vue`

```javascript
created() {
  axios.get(route(this.$route.name, this.$route.params.id, false)).then(({ data }) => {
    this.form = data.form;
    this.initialised = true;
  }).catch(error => this.handleError(error));
},
methods: {
  getDebtor () {
    axios.get('/api/endpoint').then((response) => {
      //below is where i need to get the name of the v-model object
      {:the-v-model-object-name} = response.data.value1;
    }).catch((error) => {
      this.handleError(error);
    });
  },
```
I could create that form from scratch but does not make sense to repeat code for only changing the v-model property name.

**Comment by aocneanu** [comment]
In the above context you have the form object. If you mutate this object, everything will change accordingly.

So you just need to do something like

```
findFormElement(field) {
         return this.form.attributes.find(item => item.name === field);
},
setDebtor() {
        axios.get('/api/endpoint').then(({ data }) => this.findFormElement('debtor').value  = data.value1);
}
```

**Comment by dcastrili** [comment]
Just needed to change `attributes` to `fields` but it works!

```javascript
findFormElement(field) {
    return this.form.fields.find(item => item.name === field);
},
setDebtor() {
    axios.get('/api/endpoint').then(({ data }) => this.findFormElement('debtor').value  = data.value1);
}
```

**Comment by aocneanu** [comment]
It was off the top of my head :)
