### ISSUE TITLE
vueswitch shows like vertical long line

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/FormBuilder#19]
![image](https://user-images.githubusercontent.com/8970793/37285378-d19af9a0-2639-11e8-8e79-ac23514cb6d6.png)

**Comment by aocneanu** [comment]
Is this in Enso? Or outside.

**Comment by shonhor22** [comment]
yes in enso

**Comment by aocneanu** [comment]
I suppose it's the user form?
