### ISSUE TITLE
Feature request: placeholder in input text

### ISSUE THREAD

**Issue by cosimolemma** [laravel-enso/FormBuilder#21]
Hi,
I inserted this row at line 63 in the component `VueForm.vue` in order to set a placeholder form JSON file:
`:placeholder="field.meta.placeholder"`

I hope you'll integrate this modification in your next release, this could be useful.

Thanks

**Comment by cosimolemma** [comment]
Thanks. Please remember to update it in Enso repository because in 2.4.1 version is still missing.
Thanks

**Comment by aocneanu** [comment]
I will at the next realease. Meanwhile just do an `composer update` and `npm run dev`.
