### ISSUE TITLE
when enter button click on input textfield it deselect another  fields selected value to null

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/FormBuilder#24]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Steps to Reproduce

any datatable->editform-> edit inputs text and click enter key

### Expected behavior

submit form or nothing to do
### Actual behavior

it deselect another select fields value

**Comment by aocneanu** [comment]
wrong tag in the commit..
