### ISSUE TITLE
Datepicker: Make first day of week configurable

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/FormBuilder#26]
This is  a feature request

### Description
It would be nice to have a config option for first day of week (US: sunday, Europe: monday)

### Expected behavior
Possible to set first day of week

### Actual behavior
First day of week is sunday

**Comment by aocneanu** [comment]
This is done automatically by the flatpickr's localisation.

`locale="en"`
![image](https://user-images.githubusercontent.com/16073274/38069755-aef36f4c-3320-11e8-8639-377d44e6565e.png)

`locale="de"`
![image](https://user-images.githubusercontent.com/16073274/38069767-c16ad8cc-3320-11e8-9c03-a4eb692d09cf.png)

**Comment by mauthi** [comment]
looks good, but I can't test it because locale for datepicker is not working or I forgot something to change (see last question in https://github.com/laravel-enso/Localisation/issues/36)

**Comment by aocneanu** [comment]
I guess this was also due to not using the VueFormSS, right?

**Comment by mauthi** [comment]
yes
