### ISSUE TITLE
Translate values in select

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/FormBuilder#31]
This is  a feature request.

### Description
Can we add a meta "translation" to select input fields (equal to VueDatatable)?

**Comment by aocneanu** [comment]
You should pass the translated options from the backend / frontend.

Are you familiar with Enso's `Enum` class ?

**Comment by aocneanu** [comment]
Look into `LaravelEnso\Helpers\app\Classes\Enum`. and see the methods.

And then take a look at `LaravelEnso\TutorialManager\app\Enums\Placement` and it's use in `TutorialForm`

**Comment by aocneanu** [comment]
@mauthi, can we close this?

**Comment by mauthi** [comment]
Thx, did not have time to take a look on it, but I think I can manage my needs with Enum.
