### ISSUE TITLE
does not work datepicker

### ISSUE THREAD

**Issue by arankar** [laravel-enso/FormBuilder#32]
This is  a **bug**.

### Description

![fireshot capture 4 - - http___ipcreports ipc_defect_desc_index](https://user-images.githubusercontent.com/3533923/38457978-5e63a96e-3ab1-11e8-9013-923c8909ff1a.png)

**Comment by arankar** [comment]
excuse my difficulties with English.
I use this:

`<datepicker 
            :value="testDate">
        </datepicker>`

**Comment by aocneanu** [comment]
the problem is that you are not using a theme for the datepicker.

Are you using it in Enso or outside?

**Comment by arankar** [comment]
outside

**Comment by arankar** [comment]
спасибо, разобрался!

**Comment by aocneanu** [comment]
Ok, you need to add also a theme.

https://flatpickr.js.org/themes/#usage

If you are using wepack the `require` syntax will do the trick.

If not you can also use a cdn.

And instead of `value` use `v-model` and yoy will have two way binding with `testDate`
