### ISSUE TITLE
How add joined table's column to template.json

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/FormBuilder#33]
This is  a **help request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

Is it possible form contain hasOne joined table's column and fill and save it by one click

**Comment by aocneanu** [comment]
This is not in the scope of the formbuilder package. After you submit a form you get the request object in you controller and from that on you can do whatever logic you want / need.
