### ISSUE TITLE
Money field error

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/FormBuilder#36]
This is  a **bug request**.

### Description

vue form money field always show bellow error on browsers console
### Actual behavior

> vue.common.js?2371:593 [Vue warn]: Invalid prop: type check failed for prop "precision". Expected Number, got String.
> 
> found in
> 
> ---> <Money> at resources/assets/js/components/enso/vueforms/Money.vue

**Comment by aocneanu** [comment]
Precision is a number, so when you bind it use “:precision”
