### ISSUE TITLE
when hide show button create page return an error

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/FormBuilder#38]
This is  a **bug request**.

### Description

I added 
 ```
 "actions": [
    "create",
    "store",
    "update",
    "destroy"
  ],
```
these to tableform.json for hide show button. 
### Actual behavior

Edit page's 'Save' and 'update' button appearing together.
![image](https://user-images.githubusercontent.com/8970793/40057973-59481ff2-5882-11e8-81a2-1ec2e9b851c9.png)

And create page return 500 error 
in laravel.log 

> local.ERROR: Missing required parameters for [Route: barilga.update] [URI: api/barilga/{barilga}].

**Comment by aocneanu** [comment]
For the create scenario you can't have the "update" action, and for the edit scenario you can't have the "store" action. This buttons are added under the hood without you having to do anything if you're using Enso.

If you want to specify the buttons yourself that use the `actions` helper when you build the form and specify the needed actions for each scenario
