### ISSUE TITLE
Loading Custom Component whithout slots

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/FormBuilder#42]
This is  a feature request.

### Prerequisites
* [ v] Are you running the latest version?
* [v ] Are you reporting to the correct repository?
* [v ] Did you check the documentation?
* [v ] Did you perform a cursory search?

### Description
I have a form that around 95% will be custom slot, i have made a customization that i think will decrease the number of custom slots.

### Steps to Reproduce
1 - LaravelEnso\FormBuilder\app\Classes\Attributes\Meta
in Types i added the "custom" and in Optional added "props"
2 - In template json
`{
   "label": "Label",
   "name": "name",
   "value": {},
    "meta": {
            "type": "custom",
            "content": "MyCustomComponent",
            "props": {
                 "title": "Title 1"
            }
     }
 }`
3 - in VueForm.vue i added
`<div class="control"
                   v-else-if="field.meta.type === 'custom' && field.meta.props !== undefined">
        <component v-model="field.value" :is="field.meta.content"
                              v-bind="field.meta.props || {}">
        </component>
</div>
`
![image](https://user-images.githubusercontent.com/3080041/44463774-2b7a4400-a5ef-11e8-92e3-64ba3a1454a0.png)

with this i can have any custom component whithout slots if i need to change a component prop i change in json doesn't needing javascript recompilation.

**Comment by boing6000** [comment]
![image](https://user-images.githubusercontent.com/3080041/44463806-3f25aa80-a5ef-11e8-9843-cfdb604f6108.png)

**Comment by aocneanu** [comment]
If I'm not missing something it seems to be just a workaround for one of the most powerful core architecture features that Vue offers, scoped slots. Why would you want that?

In the form you can already do something llike:

```
<vue-form ...
    ...>
    <my component slot="my-slot" :props="{ field, errors }"
         v-on="$listeners"
         v-bind="$attrs"
/>
```

The advantage of that is that you can easily implement custom logic between the fields having acces to everything from the exteriour.

**Comment by boing6000** [comment]
This way you showed it looks very interesting, however you could show an example of the component using field and errors

**Comment by aocneanu** [comment]
Did you check some of the pages from Enso? You will find a lot of examples.

The [user's edit form](https://github.com/laravel-enso/Enso/blob/master/resources/assets/js/pages/administration/users/Edit.vue) for instance uses this pattern. In the scoped slots `VueSelect` is used by passing all the relevant attirbutes from the template (`field`), and having access to the errors as well.

**Comment by boing6000** [comment]
thanks
