### ISSUE TITLE
[Suggestion] move to JSON5

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#44]
This is  a **feature request**.

### Description
switch to [json5](https://json5.org/) for the form templates to create more readable & _git-able_ json documents (also affects structuremanager)

php implementation: https://github.com/colinodell/json5

**Comment by aocneanu** [comment]
Please describe some use cases where we will benefit from this potential update.

**Comment by jlsjonas** [comment]
As described
> to create more readable & git-able json documents

For the formbuilder (which is the repo it's posted in)

[Formbuilder usage](https://docs.laravel-enso.com/packages/form-builder.html#usage)

more easily written; commentable; ...

**Comment by jlsjonas** [comment]
Why was this closed?

**Comment by aocneanu** [comment]
>Please describe some use cases where we will benefit from this potential update.

**Comment by jlsjonas** [comment]
Writing forms? the whole point of this package? I don't understand what is missing?

- comments can be added to clarify why certain things are defined the way they are (use-case: maintainability)
- better git-compatibility (use-case: better git compatibility... no double line-changes for adding a single key etc.)

...

**Comment by aocneanu** [comment]
I dont find writing comments in json a desirable "feature"

>better git-compatibility

in which sens?

>no double line-changes for adding a single key

example

**Comment by jlsjonas** [comment]
>I dont find writing comments in json a desirable "feature"
In case of dealing with big forms, the way json is used; they are

>in which sens?
The thing you quoted

>example

adding a placeholder(/anything else) to a field

**Comment by jlsjonas** [comment]
Alternatively we could also support yaml? (which would be more work; hence opting for json5 instead)
