### ISSUE TITLE
(default) select:multiple not getting filled in Vue (BE sends correct data)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#47]
This is  a **bug**.

### Prerequisites
yes I am & I did

### Description

![image](https://user-images.githubusercontent.com/932193/47223148-ca85a700-d3b8-11e8-99c0-f7bddf18ad48.png)
For some reason the values don't seem to populate on a _default_ (custom: false) select-type form field.

When inspecting (as you can see above), backend is sending the data correctly. However there's no errors whatsoever on the FE; but the Select shows "Choose" instead of the values once loaded.

name's (obviously) match; both BE & FE is also generated using the enso classes so they should match up.

### Steps to Reproduce
1. form with a non-custom, multiple (MtM) select
2. save with several selected items
3. edit, note none are marked

### Expected behavior

selected items to be selected

### Actual behavior

no selected options

**Comment by aocneanu** [comment]
the expected value is an array of ids, not of objects containing the id key. It's design to work well with laravel helpers like `$model->sync($ids)`

Perform a search for multiple: true and see what we're doing in our forms

**Comment by jlsjonas** [comment]
That's what I tried but I couldn't find any custom code (default model seemingly being used); also: it's about the render part, not the save part: I'm using `->sync` to persist the data; that works fine.

If I load the form in after saving however, it loads in with the full objects (I was also expecting it to work based solely on id's; but it's what I get from`        return ['form' => $form->edit($model)];`

**Comment by aocneanu** [comment]
look into the UserGroup -> Role relation, in the user group form.

**Comment by jlsjonas** [comment]
🤔 Looks like I'm not there yet after all:
`message: "App\Model::relationList must return a relationship instance."`

Which it can't be; as then it's returning an array of objects to the frontend 😅 

Could it be that something changed on the backend recently to avoid helper functions on the model to extract the id? but FE isn't fully updated/needs a different tag or something? (just guessing from what I see; as when I use the `roles()` equiv. I do get a correct json returned from BE (except that it's an array of objects instead of an array of ids); but when I use the `roleList` equiv. as abovel BE throws a `LogicException` that it must return a relationship instance (which... doesn't work for FE)

**Comment by jlsjonas** [comment]
🤔 looks like my github is acting out; my last 2 messages randomly disappeared 😅 

let's try again...
I did find the RoleList, plucking just the id (see snippet below); the issue is that when I use that instead of `roles` (sticking with Role for clarity) in the form json; the backend throws a `App\Model::roleList must return a relationship instance.`; which it can't as it's supposed to return an array.
```php
public function roleList()
    {
        return $this->roles()
            ->pluck('id')
            ->toArray();
    }
```

Could it be that something changed on the backend recently to avoid the helper functions? Or am I missing something obvious? 😅

**Comment by jlsjonas** [comment]
update (sorry for the double messages; it seems that github is recovering from a major storage issue at the moment)

so in the backend I have to add 
```php
            ->value('damageTypeList', $damage->damageTypeList())
```
to the edit form to make it work, as it can correctly expand from the actual relationship backend-side; I would suggest a code change to support both methods (there are likely cases where you only need/have the id's; which is presumably why it's implemented this way)

advantages:
- more intuitive configuration (it already works for saving after all)
- no helper functions _everywhere_ to edit forms with a select

I'd definitely be willing to make a PR for this.

**Comment by aocneanu** [comment]
>code change to support both methods

what methods?

**Comment by jlsjonas** [comment]
>what methods?

directly referencing the relation (i.e. array of objects) to generate the form; either backend (`edit(...)`) converts it to an id-array (`->pluck('id')`) or frontend handles it; using the available data to display (while/until the options are loaded)

advantages of the BE-based method:
- less data transfer
- simply moving _handling_ logic to the FormBuilder instead of a helper function (logic basically stays the same; i.e. only minimal code changes)

advantages of FE-based method:
- FE doesn't have to wait on the options call to display something useful (currently shows a blank/placeholder while waiting; could cause confusion)
- disabled selects (view-only) wouldn't need the extra data call (so actually saving bandwidth)

disadvantages of FE-based method:
- likely more code changes
- more data usage for editable selects
- Will have to be careful not to remove options permissions if using the _old_ method, even if read-only

**Comment by aocneanu** [comment]
>directly referencing the relation (i.e. array of objects) to generate the form; either backend (edit(...)) converts it to an id-array (->pluck('id')) or frontend handles it; using the available data to display (while/until the options are loaded)

I don't like the approach. It's a form that does already plenty of stuff, it expects data in a format, just provide the data in that format. Next idea probably would be defining also relationships and having the form to query the database for you.

For the nth time what you reported as a **bug** was not actually a **bug**, but just you not knowing how to use the lib. So with my help it was temporarily turned into a **question** only to become in the end, of course, a **"feature" request**.

**Comment by jlsjonas** [comment]
>For the nth time what you reported as a bug was not actually a bug

I would argue that, feature request aside, it is still a (documentation) _bug_, as nothing implies you need to provide it with an array of ids.

Therefore, expanding upon the _right_ way; I provided (indeed) a feature request in the hopes of improving the _UX_, and actually following conventions more (which doesn't seem to happen in this case, for once). It wouldn't make sense to define the relationships in the form, models are the place for that. And the form is actually quering the db already (options source).

the only reason I made this a feature request (as an alternative to updating the docs... which was the original issue unless the feature request got a go) is because it makes more sense not to have a helper function literally just to extract the id from relationship data that was already declared & had to be fetched to pluck it.

Right now every model using a select has to be _poluted_ with a _helper_ function per relationship that has to be _optionable_. even though it's very generic code that would(/should?) be part of the builder (as it's the form that requires the relationship in that format, vs. the _default Laravel format_.

As you like conventions, I'm surprised that you don't like the approach, as this would get the formBuilder closer to Laravel's conventions

**Comment by aocneanu** [comment]
>it is still a (documentation) bug

really?

>And the form is actually quering the db already (options source).

no, it's not, form is using an external package, that is in fact much older than the formbuilder itself

>it makes more sense not to have a helper function literally just to extract the id

then don't, just write `$form->value('roles', $model->roles()->pluck('id')`. In our case we use that helper in other places

>As you like conventions, I'm surprised that you don't like the approach, as this would get the formBuilder closer to Laravel's conventions

I love conventions but in this case I just don't see it. Again, the select is an external package.

**Comment by jlsjonas** [comment]
>really?

![image](https://user-images.githubusercontent.com/932193/47341880-7de4e900-d6a2-11e8-9e02-3812e916e31e.png)
Only showing an empty example; referencing to Enso packages; but at first glance (I went through a couple Form Controllers) I couldn't see anything different; as it was just calling `return $this->form->edit($param);` everywhere. As a _new_ user, you'd expect anything special there.

>no, it's not, form is using an external package, 
aha 👌 

>then don't, just write $form->value('roles', $model->roles()->pluck('id').

that's still _outside_ code though; for consistency I would really like to make a PR to wrap that inside FormBuilder itself; as "it just works"; except for selects, which is a shame in my (humble) opinion.

>In our case we use that helper in other places

In that case I see why _you don't see it_.

Could you share what kind of purpose that helper has besides the form options as I try to understand? I believe that most use cases will not need that helper, but I might just not be realizing something so I'm curious what it's used for.

> Again, the select is an external package.

To clarify, I'm not suggesting or implying in any way the relationships should be defined or database should be queried from Formbuilder; the model IS the place for that.
The only _issue_ I'm having is that the relationship is defined (according to Laravel spec); but that's _not enough_ for FormBuilder, even though it's just an `id` pluck from that relationship. It's not DRY (for _common_ use-cases where you don't need an id array for something else; which I don't see why you'd need that, or at least not on every model that is used as a select).

Thanks.

**Comment by jlsjonas** [comment]
Note: it seems that resizing the window triggered a call to api/meta which (correctly) redirected to login.

**Comment by aocneanu** [comment]
I've reconsider this and now think that it's a great idea. I will add it to the Form Builder.
