### ISSUE TITLE
[UX] scrollTo on validationerror

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#48]
This is  a **feature request**. (~~/UX Bug~~)

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Validationrequest rules don't make the page scroll to the errored field

### Steps to Reproduce
1. add required rules to a field
2. make sure the form is bigger than what can fit on page
3. don't enter data//enter invalid data in the required field
3. Submit (with required field out of viewport)

### Expected behavior

viewport to scroll towards the (topmost?) error

### Actual behavior

When the error is returned, the view doesn't scroll to make the error'd item visible; leading to confusion.

**Comment by aocneanu** [comment]
The idea is good.

Tell me where I can open a PR to fix a bug in your bug detection ;)

**Comment by jlsjonas** [comment]
From a UX point of view it is a _bug_: the end user can be submitting a form; the button getting disabled because of an error with no indication thereof on his screen. UX != code ;) 

And I'll open a repo for that someday 😏 (for those other times where it ended up not being a bug)  ;)

**Comment by aocneanu** [comment]
Yeah sure
