### ISSUE TITLE
Maybe a wrong explanation video in the form builder documentation?

### ISSUE THREAD

**Issue by albertosgz** [laravel-enso/FormBuilder#49]
This is  a **bug**

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Clicking in the short video in the docs, shows me how to edit a permission, not a form. Is that correct?

### Steps to Reproduce
In the [Form Builder documentation](https://docs.laravel-enso.com/packages/form-builder.html), click on the short video at the begining

### Expected behavior
A video setting up a form, creating a new one or editing an already existing one.

### Actual behavior
Displays a video setting up a permission.

**Comment by aocneanu** [comment]
Oh, I see the confusion.. for most of the packages we have short presentation videos where we only show some of the capabilities.

Maybe at some point we will have video tutorials with coding steps but I don't expect this to happen too soon.

If you browse through the app you will see different implementation scenarios and you can also peek  in the code to see how's implemented. Together with the existing docs and the support on github you should be able to build something without too much effort.

**Comment by albertosgz** [comment]
This issue was more related to let you know if such video was a mistake or not.

But, as you say, I think I can find out the way to code new forms.

Thanks!
