### ISSUE TITLE
Allow setting a custom column width programmatically

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#55]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Just like we can set custom values & meta values; allow setting the column programmatically.

Use case: a certain flag indicates if we need a 2/3 or half width field

### Example implementation

```php
$this->form->column($field, $value);
```

**Comment by aocneanu** [comment]
Please give me examples when this would be useful.

**Comment by jlsjonas** [comment]
We have an informative column (shown during the editing process only) that usually requires a wider view (2/3); however, in some cases the (computed) data in it is quite brief which makes the interface look funky if that column is still shifted to the left.

**Comment by aocneanu** [comment]
For the moment I see too many implications and no clean implementation for something that I would probably never use.

Feel free to open a PR for this if you can find a clean implementation...
