### ISSUE TITLE
How to work with type date? Datepicker

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/FormBuilder#57]
This is not a bug I think but a question. I have my model as datetime but when I try to save form filling the date on datepicker I got error.

I have this date on my database "2018-12-04 00:00:00"
It appears on datepicker like: 08/08/2023

If I set the date with datepicker I get error 500.

entityTest.json
         "fields": [ {
                "label": "Field Date",
                "name": "field_date",
                "value": null,
                "meta": {
                    "type": "datepicker",
                    "time": false,
                    "format": "m/d/Y"
                }
            }];

On my edit request I receive the correct data: "name":"field_date","value":"2019-12-04 00:00:00"

### Prerequisites
* [ ] Are you running the latest version? YES
* [ ] Are you reporting to the correct repository? YES
* [ ] Did you check the documentation? YES
* [ ] Did you perform a cursory search? YES

**Comment by gandesc** [comment]
Hi,

Can you make sure that within your model you are casting the attribute to date?

```php
protected $dates = ['field_date'];
```

**Comment by elysiopires** [comment]
Hi @gandesc !

Thank you for your help...

I added the protected $dates to my model.

Now error changes: 
I receive this response when I try to update (patch):
{
    "message": "Unexpected data found.\nUnexpected data found.\nData missing",
    "exception": "InvalidArgumentException",
    "file": "/price2go/vendor/nesbot/carbon/src/Carbon/Carbon.php",
    "line": 775,
    "trace": [
        {
            "file": "/price2go/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 748,
            "function": "createFromFormat",
            "class": "Carbon\\Carbon",
            "type": "::"
        },

and when enter on form... if I hard set a date on db... on datepicker appears [object Object] instead of 12/08/2018

Best,
Elysio

**Comment by aocneanu** [comment]
Hi @elysiopires,

When working with dates you want to:

- add the date fields in the `protected $dates = [..]` array
- set the field as `datepicker` in the JSON form template, optionally specify the `format`
- if the format is different from the the DB format than add a setter in your model that will transform the date accordingly

An example implementation to follow is the `birthday` attribute in `Person.php` / `person.json`.

If you still have issues let us know.

**Comment by aocneanu** [comment]
Can we close this?

**Comment by elysiopires** [comment]
Sure!

Thx for the quickly answer!

Best, Elysio

**Comment by aocneanu** [comment]
You're supposed to close your issues once they are resolved.

>when the issue is resolved, don't forget to **CLOSE** it
