### ISSUE TITLE
Can't pass additional params to VueForm serverside

### ISSUE THREAD

**Issue by gagishmagi** [laravel-enso/FormBuilder#59]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I had read the documentation really carefully and tried to do it in couple different ways but with no success.
I just can't understand how to pass additional params to some VueForm component.
From what I understand There was an old component called EnsoFrom which is a wrapper for the VueForm component which is named VueFormSs that stands for Vue Form Server side component. That uses the Form builder to build the forms and the button/actions to make Rest requests (POST/PUT/DELETE...) What I need to do is I have a form for some Module let's call it "ShopingCart" I want to add "Item"s to this cart but I need another Model called "Product" to get the prod_id which is an attribute on the "Item" every item is a product. The problem is I can't Understand how to pass the "prod_id" to the Form builder data which then will be Passed on to the ValidatedFormRequest, that I will use in the controller. 
I read about the "params" prop that suppose to do just that and that they are 2 diffrent params one for the **client side / vuejs** and the other for the **server side** which from what I can tell is exactly what I need. I took the example of Addresses component and the Contacts component which pass additional additional data like 'addressable_id', 'addressable_type' and use a component called MorphableContainer for that. But the param I am trying to pass is not Morphable just one prod_id. Hope I was able to explain myself as good as possible.

### Steps to Reproduce

1. Create a VueComponent page like Index.vue
2. Add a VueForm component to it or inheret and costomize it.
3. Set the params prop on it to be as such:
computed: {
    params() {
        return {
            prod_id: 1,
        };
    },
  },
4. use axios to call route 'something.create' to get form data, 
console.log the response and look for the params you passed.
5. Go to the server side and dump the validated $request data
and you won't see your additional params. 

### Expected behavior

var_dump($request->all()):
somedata...
array{
   prod_id => 1
}

### Actual behavior

var_dump($request->all()):
somedata...

**Comment by gandesc** [comment]
Hi @gagishmagi 

![image](https://user-images.githubusercontent.com/14071925/52054405-107c0a80-2565-11e9-9461-e50eedf04be6.png)
![image](https://user-images.githubusercontent.com/14071925/52054428-24c00780-2565-11e9-8fd5-cbdcf5698c2b.png)
![image](https://user-images.githubusercontent.com/14071925/52054446-3b665e80-2565-11e9-8a44-590032fae0b7.png)

I understand that you're using the form within the Enso ecosystem, in which case you want to use the enso-form vue component.

> From what I understand There was an old component called EnsoFrom which is a wrapper for the VueForm component which is named VueFormSs that stands for Vue Form Server side component.

EnsoForm replaced VueFormSS. Both are wrappers for VueForm. If you set the params on the wrapper (EnsoForm), VueForm will receive them as well.

![image](https://user-images.githubusercontent.com/14071925/52054663-ec6cf900-2565-11e9-99d9-6eec568ae131.png)


There should no longer be any mention of VueFormSS in the documentation. If you have suggestions on how to improve it, please let us know - you may even make a [contribution/pull request](https://github.com/laravel-enso/Documentation).

**Comment by gagishmagi** [comment]
I do see it on the client side though:
![image](https://user-images.githubusercontent.com/9334602/52061840-f26bd580-2577-11e9-9f5b-421f660289de.png)

**Comment by gagishmagi** [comment]
Thank you, 
I will consider doing it, but I would really like to find out the source of this issue...
laravel-enso/formbuilder              2.10.16                Form builder for Laravel Enso

**Comment by gandesc** [comment]
Hi,

This is a bug that was fixed in a later iteration, via the commit: 1d1258dd4b9a8fcae2a9c76a744199f391181fcd (take a look inside to see what it entails :smiley: ).

If you do a general `composer update` or a specific `composer update laravel-enso/formbuilder` you could update to a newer version that contains the fix.

**Comment by gagishmagi** [comment]
WOW, Thank you so much gandesc, I would never even consider this to be the case...
Thanks guys, I thought I was loosing my mind... :+1:
