### ISSUE TITLE
Support one of SelectField's param fields from EnsoForm

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#60]
This is  a **feature request**. (will provide PR after discussions on implementation method as we have several options)

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Currently, Selectfield (and thus VueSelect) have `params`, `custom-params` & `pivot-params` to support passing along extra metadata to the options query server-side. (mostly used for datatables? limited documentation)
However, none of these are exposed to VueForm.

### Suggestion
Add a `params` optional meta on Select fields, exposing it to VueSelect (`metaParams` to avoid conflict with existing structure & remain consistent with what's in place?)

### Example use case

Having a parent selector, of the same type.
The item that it's about should not be included in the query

**Comment by jlsjonas** [comment]
As I've been revising this more we might consider adding an parent-specific tag after all, as more complex use-cases will be more likely to have a custom field anyway; and the options request currently does not have a straightforward way of figuring out the "requested" id anyway (except for parsing the HTTP_REFERER perhaps)

### Alternative suggestion
add a `hideself`, `isparent` or similar meta boolean that adds the model's id to the request allowing the back-end code to exempt it from the result set (either automatically or by making it available to `query()` to allow custom logic)

**Comment by aocneanu** [comment]
The reason the three objects are not exposed to the json template is because this params are meant to be dynamic. To use them make the necessary fields custom and play with the them in the view.

There are a few examples in Enso already.

**Comment by jlsjonas** [comment]
I already use them in custom form in multiple occasions, the issue is that the custom field feels very overkill when just trying to hide "itself"

i.e. any Model containing a `parent_id`, when editing the original parent would be present by default, having the potential to cause an infinite loop.
The fix is simply exempting the _edited_ Model's id; which seems like a very common use-case.

I understand why the current ones are not exposed towards static json; hence also the revised suggestion in the comment.

**Comment by aocneanu** [comment]
I believe that with the new syntax (3.1) the custom fields should not be overkill at all. Can we close this?

**Comment by aocneanu** [comment]
Or if you want, you could draft a PR, but I would suggest pseudo code only at this stage.

**Comment by jlsjonas** [comment]
given the fact that route params no longer use the `id` key but the object's name; along with the new syntax I believe the custom field strategy is the best approach indeed.
