### ISSUE TITLE
Money-type model's value only updated on blur

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#61]
This is  a **UX inconsistency**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

`resources/js/components/enso/vueforms/Money.vue` uses a separate property to store the input value in; updating the value prop on blur.

This makes it possible to _succesfully_ save a money-type field without the new value actually being passed along

### Steps to Reproduce
1. Have a form with a money-type field
2. Add/edit a value and press enter (or other action that submits the form without blurring out of the field first)
3. Note that the submitted value is still the original

### Expected behavior

Form's value to be updated before submit (especially since it appears to be saved towards the user, new value is preserved & confirmation message is shown)

### Actual behavior

Appears to get saved (new value is preserved in FE & "was successfully updated" is shown) however the back-end never received the field.

### Possible workaround/fixes

Watch for `keyCode == 13`(enter) on `keydown` & either preventDefault or update value.
Note that adding (in `Money.vue`)
`        @keydown="(e)=> { if(e.keyCode == 13) update(e) }"` caused the value to become 0 on _actual blur_, `        @keydown="(e)=> { if(e.keyCode == 13) e.preventDefault() }"` seems to fix it fine, but not all cases have been tested (mobile? other methods?)

**Comment by jlsjonas** [comment]
Whoops... didn't mean to commit to master 😅 
Feel free to reopen if not satisfied with the solution @aocneanu

**Comment by aocneanu** [comment]
let's replace the js with `@keydown.enter="update"`. Commit again on master, but not from now on :)

Thanks

**Comment by jlsjonas** [comment]
Totally forgot about the `.enter` shorthand, thanks for the reminder! (and sorry for the to-master accident, I'll double-check before ctrl-entering from now on 😅 )
