### ISSUE TITLE
Get form data in custom method

### ISSUE THREAD

**Issue by VadimsTalapins** [laravel-enso/FormBuilder#63]
This is feature request.

### Prerequisites
* [✓] Are you running the latest version?
* [✓] Are you reporting to the correct repository?
* [✓] Did you check the documentation?
* [✓] Did you perform a cursory search?

### Description

I made a form using laravel-enso, and add a custom button width custom action. How do I get all the form parameters that have been entered and selected in my method. I am a beginner in vue sorry.
```
<enso-form class="box has-background-light raises-on-hover animated fadeIn" @loaded="ready = true;">
                <a slot="actions"
                    class="button is-warning"
                    @click="addNotes"
                    v-if="loading">
                    <span class="is-hidden-mobile">
                        {{ __('Add note') }}
                    </span>
                    <span class="icon">
                        <fa icon="user-tie"/>
                    </span>
                    <span class="is-hidden-mobile"/>
                </a>
				 </enso-form>
methods: {
  addNotes() {
??????????
}
}
```

**Comment by gandesc** [comment]
Hi Vadims,

add a ref property+value on the enso-form, then use the `this.$refs.myRef.data` syntax within your method to access the form data, where `myRef` is the ref attribute value. 

VueJs [ref docs](https://vuejs.org/v2/api/#ref)

**Comment by VadimsTalapins** [comment]
@gandesc Thank you so much!

For starters like me :D

I add this in enso-form
`<enso-form ref="formRef" ...>`

and in my method
this.$refs.formRef.formData() this returns form data

**Comment by VadimsTalapins** [comment]
@gandesc Thank you so much!

For starters like me :D

I add this in enso-form
`<enso-form ref="formRef" ...>`

and in my method
this.$refs.formRef.formData() this returns form data
