### ISSUE TITLE
select source conversion moved to backend?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#64]
This is  a **bug | feature request**. (unexpected change, more _useless_ BE processing)

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

It looks like the Enso BE is reforming the source route to a FQDN+path instead of the permission-based notation?
This causes unexpected errors in several places and seems like a change that shouldn't have happened as it causes extra BE load by reforming the source during parsing (vs. near-static forwarding) & reduces its flexibility (it breaks & prevents our custom logic behind a field to work, with no apparent workaround due to the whitelisted nature of the Formbuilder template parameters).

### Steps to Reproduce
1. Inspect source of a form create call

### Expected behavior

Source not to be modified

### Actual behavior

Source gets modified from a permission-like parameter to a full url, preventing the use of the `custom.model.options`-style from FE (or having dynamic fields that alter between input & select) + causing more data on every request.

**Comment by jlsjonas** [comment]
Quick & dirty fix in `node_modules/@enso-ui/select/src/renderless/CoreSelect.vue`'s `fetch()` method update the first axios.get parameter to:
```js
axios.get(!this.source.startsWith('http') && typeof route === 'function' ? route(this.source) : this.source,
```

Shared for inspirational (or temporary workaround) use.

**Comment by aocneanu** [comment]
>It looks like the Enso BE is reforming the source route to a FQDN+path instead of the permission-based notation?

True, the builder is used now to "build" the path too.

>This causes unexpected errors in several places and seems like a change that shouldn't have happened as it causes extra BE load by reforming the source during parsing (vs. near-static forwarding) & reduces its flexibility (it breaks & prevents our custom logic behind a field to work, with no apparent workaround due to the whitelisted nature of the Formbuilder template parameters).

That should definitely not be the case. 

Please share the code where you encounter this problem(s).

**Comment by jlsjonas** [comment]
>That should definitely not be the case.

- the builder only builds the source url if the `json` type is select, for compatibility reasons we have that specific field set to input but we're using the select field meta along with it (the input is sourced from a select within the custom slot)
- It's preventing a `canAccess` check on the FE for those fields (not using it for that purpose at the moment but I feel like it should be pointed out)

Either way, IMHO feel like this is something that should be left up for the FE to keep the most flexibility by default

**Comment by aocneanu** [comment]
For the first bullet ... beats my imagination, still waiting for code exaple.

For the second, it does not prevent canAccess, that being an implementation decision. You can still have a custom field wrapped in a canAccess directive.

**Comment by jlsjonas** [comment]
> still waiting for code example.

I'm unable to share the full example, but I have a custom component for the create-part of a _simple_ `input` field. The custom component uses (amongst other things) a select-field (for which I was using the meta-source.

> You can still have a custom field wrapped in a canAccess directive.

Yes, but it can no longer use the meta source for the check.



Am I missing some obvious advantage of moving the url generation to the BE? As I can only see downsides from it 😅

**Comment by aocneanu** [comment]
>I'm unable to share the full example,

Sorry :)

>Yes, but it can no longer use the meta source for the check.

Why?

>Am I missing some obvious advantage of moving the url generation to the BE? As I can only see downsides from it

It's just a simple normalisation, that potentially breaks some hacks

Note that the route check and processing in the builder happens only when  this is met `if ($meta->get('type') === 'select')`, you were talking something about `input`...

**Comment by jlsjonas** [comment]
>Why?

Because it's no longer a `permission.matchin.route` but a full path

>It's just a simple normalisation

It feels like a denormalisation tbh, everything is based on `dot.notation.route` except for the sources 😬 

>you were talking something about input

Correct, because `<select-field>` expects a full path instead of the dot-nation now.

**Comment by aocneanu** [comment]
>Because it's no longer a permission.matchin.route but a full path

ah lol

>It feels like a denormalisation tbh, everything is based on dot.notation.route except for the sources 😬
![image](https://user-images.githubusercontent.com/16073274/55083204-c9fde480-50ab-11e9-9c23-6e3a7fad67ce.png)

**Comment by jlsjonas** [comment]
>define everything

Menus, notifications, ...
i.e. everything (except for the buttons, clearly 😁 )

>You have the option of appending data in the backend instead of hacking extra fields

I know, this just worked best for us as the same field only needs the _special_ input mechanism during create.

This was actually a reiteration as I was using a separate field/parameter at first.

I could technically fix this specific issue (besides the workaround posted above) by marking the field as a select in the create but I still feel like this would limit future flexibility.

Either way... I'm fine with this getting closed (there's a question mark in the title for a reason) but the changelog/release notes should probably note this change if it's staying

**Comment by aocneanu** [comment]
so its a field that you only need on edit, not create?

**Comment by jlsjonas** [comment]
No, it's just being handled differently on edit.

**Comment by aocneanu** [comment]
>Either way... I'm fine with this getting closed (there's a question mark in the title for a reason) but the changelog/release notes should probably note this change if it's staying

At least we will have this issue for anybody concerned. I'll close it for now.
