### ISSUE TITLE
Update VueFormInput

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/FormBuilder#8]
starting with 2.5.0 Vue supports dynamic type for input fields with v-model 

https://github.com/vuejs/vue/commit/f3fe012d5499f607656b152ce5fcb506c641f9f4

**Comment by mauthi** [comment]
I was looking for the same - maybe you can add a snippet for this to documentation after you changed code?

**Comment by aocneanu** [comment]
@mauthi please elaborate.
